version: "3.7"

services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/postgres/init:/docker-entrypoint-initdb.d
    env_file:
      - .env

  server:
    build: .
    container_name: server
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - ./server:/go/src/server
    working_dir: /go/src/server
    depends_on:
      - postgres
    env_file:
      - .env
