version: "3.7"

services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    #   POSTGRES_PASSWORD: postgres
    #   POSTGRES_USER: postgres
    #   POSTGRES_DB: postgres
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/postgres/init:/docker-entrypoint-initdb.d
    env_file:
      - .env

  server:
    image: golang:1.20.1
    container_name: server
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./server:/go/src/server
    working_dir: /go/src/server
    command: go run main.go
    depends_on:
      - postgres
    env_file:
      - .env
